### ISSUE TITLE
Install error (importlib)

### ISSUE THREAD

**Issue by Sivolen** [DanSheps/netbox-config-backup#7]
### Plugin version

v1.0.2

### netbox-plugin-extensions version

v1.0.4

### NetBox version

v3.1.6

### Python version

3.8

### Steps to Reproduce

Hi 
1. I have an error when I install this plugin 
```
(.venv) a.gridnev@netbox:/opt/netbox/venv/bin$ pip install netbox-config-backup
Collecting netbox-config-backup
  Using cached netbox_config_backup-1.0.2-py3-none-any.whl (29 kB)
Collecting netbox-plugin-extensions
  Downloading netbox_plugin_extensions-1.1.1-py3-none-any.whl (19 kB)
Collecting uuid
  Downloading uuid-1.30.tar.gz (5.8 kB)
Collecting dulwich
  Using cached dulwich-0.20.32-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (549 kB)
Collecting importlib
  Using cached importlib-1.0.4.zip (7.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/scripts/netbox-sync/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4pqiys82/importlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4pqiys82/importlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4pqiys82/importlib/pip-egg-info
         cwd: /tmp/pip-install-4pqiys82/importlib/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/scripts/netbox-sync/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/usr/lib/python3.8/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/usr/lib/python3.8/distutils/dist.py", line 19, in <module>
        from distutils.util import check_environ, strtobool, rfc822_escape
      File "/usr/lib/python3.8/distutils/util.py", line 9, in <module>
        import importlib.util
    ModuleNotFoundError: No module named 'importlib.util'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(.venv) a.gridnev@netbox:/opt/netbox/venv/bin$ python3 --version
Python 3.8.10

```
Can you help me how to install it? 

### Expected Behavior

No response

### Observed Behavior

No response

**Comment by DanSheps** [comment]
Hello,

This is a pip/python problem, I would try rebuilding your venv then try installing it again.
