### ISSUE TITLE
Plugin Configuration arguments bug

### ISSUE THREAD

**Issue by gurfatehsingh** [DanSheps/netbox-config-backup#75]
### Plugin version

v.1.4.7

### NetBox version

v3.5.6

### Python version

3.8

### Steps to Reproduce

Followed the steps in the readme.

### Expected Behavior

python3 manage.py migrate

Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, netbox_config_backup, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  Applying netbox_config_backup.0001_initial... OK
  Applying netbox_config_backup.0002_git_models... OK
  Applying netbox_config_backup.0003_primary_model_to_bigid... OK
  Applying netbox_config_backup.0004_custom_constraints... OK
  Applying netbox_config_backup.0005_commit_add_time_field... OK
  Applying netbox_config_backup.0006_backup_add_commit_last_time... OK
  Applying netbox_config_backup.0007_backup_job_add_scheduled... OK
  Applying netbox_config_backup.0008_backupjob_scheduled_nullable... OK
  Applying netbox_config_backup.0009_bctc_file_model_backup_fk_restructure...
!!!WARNING!!!
Once this migration operation is complete, it is not recommended to revert it
 OK
  Applying netbox_config_backup.0010_backup_ip... OK
  Applying netbox_config_backup.0011_alter_backup_name... OK
  Applying netbox_config_backup.0012_backup_status... OK
  Applying netbox_config_backup.0013_backup__to_netboxmodel... OK

### Observed Behavior

python3 manage.py migrate

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 97, in handle
    self.check(databases=[database])
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/urls.py", line 8, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox/netbox/extras/plugins/urls.py", line 31, in <module>
    urlpatterns = import_string(f"{plugin_path}.urls.urlpatterns")
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_config_backup/urls.py", line 2, in <module>
    from . import views
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_config_backup/views.py", line 13, in <module>
    from netbox_config_backup.git import GitBackup
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_config_backup/git.py", line 182, in <module>
    repository = GitBackup()
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_config_backup/git.py", line 42, in __init__
    self.repository = repo.Repo.init(self.location, True)
TypeError: Repo.init() takes 2 positional arguments but 3 were given

This was solved by editting: git.py, line 42. Removed (True) from the Line.

**Comment by DanSheps** [comment]
I just checked, it looks like the latest dulwich makes the mkdir parameter not positional.  There will be a push shortly to correct.
