### ISSUE TITLE
Upgrade from netbox 3.7.3 to 4.0.3

### ISSUE THREAD

**Issue by dangerbock** [DanSheps/netbox-config-backup#95]
### Plugin version

1.5.4

### NetBox version

3.7.3

### Python version

3.8

### Steps to Reproduce

got this error when trying to upgrade netbox from 3.7.3 to 4.0.3

Installing collected packages: text-unidecode, sgmllib3k, paginate, nh3, aniso8601, watchdog, urllib3, uritemplate, tzdata, typing-extensions, tablib, svgwrite, sqlparse, six, rpds-py, regex, PyYAML, pytkdocs, PyJWT, pygments, pycparser, psycopg-c, prometheus-client, platformdirs, Pillow, pathspec, packaging, oauthlib, netaddr, mkdocs-material-extensions, mergedeep, mdurl, MarkupSafe, Markdown, inflection, idna, graphql-core, feedparser, defusedxml, colorama, click, charset-normalizer, certifi, babel, attrs, async-timeout, requests, referencing, redis, pyyaml-env-tag, python3-openid, python-dateutil, pymdown-extensions, psycopg-pool, psycopg, promise, mkdocs-get-deps, markdown-it-py, Jinja2, gunicorn, graphql-relay, django-prometheus, django-pglocks, cffi, asgiref, strawberry-graphql, rq, rich, requests-oauthlib, jsonschema-specifications, graphene, ghp-import, Django, cryptography, strawberry-graphql-django, social-auth-core, mkdocs, jsonschema, graphene-django, drf-spectacular-sidecar, djangorestframework, django-timezone-field, django-taggit, django-tables2, django-rq, django-rich, django-redis, django-js-asset, django-htmx, django-filter, django-debug-toolbar, django-cors-headers, social-auth-app-django, mkdocs-material, mkdocs-autorefs, drf-spectacular, django-mptt, django-graphiql-debug-toolbar, mkdocstrings, mkdocstrings-python-legacy
Successfully installed Django-5.0.6 Jinja2-3.1.4 Markdown-3.6 MarkupSafe-2.1.5 Pillow-10.3.0 PyJWT-2.8.0 PyYAML-6.0.1 aniso8601-9.0.1 asgiref-3.8.1 async-timeout-4.0.3 attrs-23.2.0 babel-2.15.0 certifi-2024.6.2 cffi-1.16.0 charset-normalizer-3.3.2 click-8.1.7 colorama-0.4.6 cryptography-42.0.8 defusedxml-0.8.0rc2 django-cors-headers-4.3.1 django-debug-toolbar-4.3.0 django-filter-24.2 django-graphiql-debug-toolbar-0.2.0 django-htmx-1.17.3 django-js-asset-2.2.0 django-mptt-0.16.0 django-pglocks-1.0.4 django-prometheus-2.3.1 django-redis-5.4.0 django-rich-1.8.0 django-rq-2.10.2 django-tables2-2.7.0 django-taggit-5.0.1 django-timezone-field-6.1.0 djangorestframework-3.15.1 drf-spectacular-0.27.2 drf-spectacular-sidecar-2024.5.1 feedparser-6.0.11 ghp-import-2.1.0 graphene-3.3 graphene-django-3.2.1 graphql-core-3.2.3 graphql-relay-3.2.0 gunicorn-22.0.0 idna-3.7 inflection-0.5.1 jsonschema-4.22.0 jsonschema-specifications-2023.12.1 markdown-it-py-3.0.0 mdurl-0.1.2 mergedeep-1.3.4 mkdocs-1.6.0 mkdocs-autorefs-1.0.1 mkdocs-get-deps-0.2.0 mkdocs-material-9.5.24 mkdocs-material-extensions-1.3.1 mkdocstrings-0.25.1 mkdocstrings-python-legacy-0.2.3 netaddr-1.2.1 nh3-0.2.17 oauthlib-3.2.2 packaging-24.0 paginate-0.5.6 pathspec-0.12.1 platformdirs-4.2.2 prometheus-client-0.20.0 promise-2.3 psycopg-3.1.19 psycopg-c-3.1.19 psycopg-pool-3.2.2 pycparser-2.22 pygments-2.18.0 pymdown-extensions-10.8.1 python-dateutil-2.9.0.post0 python3-openid-3.2.0 pytkdocs-0.16.1 pyyaml-env-tag-0.1 redis-5.0.4 referencing-0.35.1 regex-2024.5.15 requests-2.32.2 requests-oauthlib-2.0.0 rich-13.7.1 rpds-py-0.18.1 rq-1.16.2 sgmllib3k-1.0.0 six-1.16.0 social-auth-app-django-5.4.1 social-auth-core-4.5.4 sqlparse-0.5.0 strawberry-graphql-0.230.0 strawberry-graphql-django-0.40.0 svgwrite-1.4.3 tablib-3.6.1 text-unidecode-1.3 typing-extensions-4.12.1 tzdata-2024.1 uritemplate-4.1.1 urllib3-2.2.1 watchdog-4.0.1
Installing local dependencies (pip install -r local_requirements.txt)...
Collecting netbox-ipv4-tools (from -r local_requirements.txt (line 1))
  Using cached netbox_ipv4_tools-1.0.4-py3-none-any.whl.metadata (2.2 kB)
Using cached netbox_ipv4_tools-1.0.4-py3-none-any.whl (14 kB)
Installing collected packages: netbox-ipv4-tools
Successfully installed netbox-ipv4-tools-1.0.4
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/settings.py", line 753, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'netbox_config_backup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 104, in wrapper
    saved_locale = translation.get_language()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 211, in get_language
    return _trans.get_language()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 66, in __getattr__
    if settings.USE_I18N:
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 756, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin netbox_config_backup: Module not found. Check that the plugin module has been installed within the correct Python environment.

### Expected Behavior

...

### Observed Behavior

...

**Comment by DanSheps** [comment]
Is netbox_config_backup in your python environment?

**Comment by dangerbock** [comment]
how can i make sure it is ?

**Comment by DanSheps** [comment]
`pip show netbox-config-backup`

Should report:

```
Name: netbox-config-backup
Version: 2.0.1
Summary: NetBox Configuration Backup
Home-page: https://github.com/dansheps/netbox-config-backup/
Author: Daniel Sheppard
Author-email: dans@dansheps.com
License: Proprietary
Location: /opt/netbox-config-backup
Editable project location: /opt/netbox-config-backup
Requires: deepdiff, dulwich, napalm, netbox-napalm-plugin, netmiko, pydriller, uuid
Required-by:
```
